spring:
  application:
    name: order-service
server:
  port: 8080

rabbitmq:
  queue:
    order:
        name: order-email-queue
    email:
        name: email-queue
  topic-exchange:
      name: order-topic-exchange
  routing-key:
    order:
      name: order-routing-key
    email:
      name: email-routing-key
